---
name: "BlockSniper"
version: 0.0.99
api: 3.0.0-ALPHA2
author: "Sandertv"
main: Sandertv\BlockSniper\Loader

permissions:
    blocksniper:
        default: false
        description: "Allows access to all BlockSniper features."
        children:
            blocksniper.command:
                default: false
                description: "Allows access to all BlockSniper command features."
                children:
                    blocksniper.command.snipe:
                        default: op
                        description: "Allows access to the snipe command."
                    blocksniper.command.brushwand:
                        default: op
                        description: "Allows access to the brush wand command."
            blocksniper.type:
                default: false
                description: "Allows access to all BlockSniper types."
                children:
                    blocksniper.type.overlay:
                        default: op
                        description: "Allows access to the overlay type."
                    blocksniper.type.layer:
                        default: op
                        description: "Allows access to the layer type"
                    blocksniper.type.replace:
                        default: op
                        description: "Allows access to the replace type"
            blocksniper.shape:
                default: false
                description: "Allows access to all BlockSniper shapes."
                children:
                    blocksniper.shape.sphere:
                        default: op
                        description: "Allows access to the sphere shape."
                    blocksniper.shape.cuboid:
                        default: op
                        description: "Allows access to the cuboid shape."
                    blocksniper.shape.standingcylinder:
                        default: op
                        description: "Allows access to the standing cylinder shape."
...
